{% set name = "koalas" %}
{% set version = "0.27.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34c2a813eae76cec03b2431173883a7e453c706e41be6f29fece0a90a8ee2274

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5,<3.8
  run:
    - matplotlib-base >=3.0.0
    - numpy >=1.14
    - pandas >=0.23.2,<1.0
    - pyarrow >=0.10,<0.15
    - python >=3.5

test:
  requires:
    - pyspark >=2.4
  imports:
    - databricks
    - databricks.koalas
    - databricks.koalas.missing

about:
  home: https://github.com/databricks/koalas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pandas API on Apache Spark
  doc_url: https://koalas.readthedocs.io/
  dev_url: https://github.com/databricks/koalas

extra:
  recipe-maintainers:
    - rxin
    - thunterdb
    - gatorsmile
    - HyukjinKwon
    - ueshin
